[package]
name = "zdocker"
version = "0.1.0"
authors = ["Axel Magnuson <axelmagn@gmail.com>"]

[dependencies]
docopt          = "0.6"
env_logger      = "0.3"
log             = "0.3"
rustc-serialize = "0.3"
toml            = "0.2"
